package org.generationcp.breeding.manager.application;


public enum Message{
    MAIN_WINDOW_CAPTION
    ,BACK
    ,DONE
    ,ERROR_INTERNAL
    ,ERROR_PLEASE_CONTACT_ADMINISTRATOR
    ,GERMPLASM_BREEDING_METHOD_LABEL
    ,GERMPLASM_DATE_LABEL
    ,GERMPLASM_DETAILS_LABEL
    ,GERMPLASM_LOCATION_LABEL
    ,GERMPLASM_NAME_TYPE_LABEL
    ,I_WANT_TO_IMPORT_GERMPLASM_LIST
    ,IMPORT_GERMPLASM_LIST_TAB_LABEL
    ,IMPORT_PEDIGREE_OPTION_ONE
    ,IMPORT_PEDIGREE_OPTION_TWO
    ,IMPORT_PEDIGREE_OPTION_THREE
    ,LIST_DATE_LABEL
    ,LIST_DESCRIPTION_LABEL
    ,LIST_NAME_LABEL
    ,LIST_TYPE_LABEL
    ,NEXT
    ,OPEN_GERMPLASM_IMPORT_FILE
    ,PEDIGREE_OPTIONS_LABEL
    ,SAVE_GERMPLASM_LIST
    ,SELECT_GERMPLASM_LIST_FILE
    ,SPECIFY_GERMPLASM_DETAILS
    ,UPLOAD
    ,WELCOME_LABEL
    ,WELCOME_QUESTION_LABEL
    ,WELCOME_TAB_LABEL
}
